/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as CreateOrganizationRouteImport } from './routes/create-organization'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProfileSplatRouteImport } from './routes/user-profile.$'
import { Route as SupportDocsRouteImport } from './routes/support.docs'
import { Route as SupportContactRouteImport } from './routes/support.contact'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as PricingWalletRouteImport } from './routes/pricing.wallet'
import { Route as PricingSubscriptionsRouteImport } from './routes/pricing.subscriptions'
import { Route as OrganizationProfileAcceptInvitationRouteImport } from './routes/organization-profile.accept-invitation'
import { Route as OrganizationProfileSplatRouteImport } from './routes/organization-profile.$'
import { Route as ApiChatUsageRouteImport } from './routes/api.chat-usage'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileSplatRoute = UserProfileSplatRouteImport.update({
  id: '/user-profile/$',
  path: '/user-profile/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportDocsRoute = SupportDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => SupportRoute,
} as any)
const SupportContactRoute = SupportContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SupportRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingWalletRoute = PricingWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => PricingRoute,
} as any)
const PricingSubscriptionsRoute = PricingSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => PricingRoute,
} as any)
const OrganizationProfileAcceptInvitationRoute =
  OrganizationProfileAcceptInvitationRouteImport.update({
    id: '/organization-profile/accept-invitation',
    path: '/organization-profile/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationProfileSplatRoute =
  OrganizationProfileSplatRouteImport.update({
    id: '/organization-profile/$',
    path: '/organization-profile/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatUsageRoute = ApiChatUsageRouteImport.update({
  id: '/api/chat-usage',
  path: '/api/chat-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chat': typeof ChatRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/pricing': typeof PricingRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/api/chat-usage': typeof ApiChatUsageRoute
  '/organization-profile/$': typeof OrganizationProfileSplatRoute
  '/organization-profile/accept-invitation': typeof OrganizationProfileAcceptInvitationRoute
  '/pricing/subscriptions': typeof PricingSubscriptionsRoute
  '/pricing/wallet': typeof PricingWalletRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/support/contact': typeof SupportContactRoute
  '/support/docs': typeof SupportDocsRoute
  '/user-profile/$': typeof UserProfileSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chat': typeof ChatRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/pricing': typeof PricingRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/api/chat-usage': typeof ApiChatUsageRoute
  '/organization-profile/$': typeof OrganizationProfileSplatRoute
  '/organization-profile/accept-invitation': typeof OrganizationProfileAcceptInvitationRoute
  '/pricing/subscriptions': typeof PricingSubscriptionsRoute
  '/pricing/wallet': typeof PricingWalletRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/support/contact': typeof SupportContactRoute
  '/support/docs': typeof SupportDocsRoute
  '/user-profile/$': typeof UserProfileSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chat': typeof ChatRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/pricing': typeof PricingRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/api/chat-usage': typeof ApiChatUsageRoute
  '/organization-profile/$': typeof OrganizationProfileSplatRoute
  '/organization-profile/accept-invitation': typeof OrganizationProfileAcceptInvitationRoute
  '/pricing/subscriptions': typeof PricingSubscriptionsRoute
  '/pricing/wallet': typeof PricingWalletRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/support/contact': typeof SupportContactRoute
  '/support/docs': typeof SupportDocsRoute
  '/user-profile/$': typeof UserProfileSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/chat'
    | '/create-organization'
    | '/pricing'
    | '/support'
    | '/api/chat-usage'
    | '/organization-profile/$'
    | '/organization-profile/accept-invitation'
    | '/pricing/subscriptions'
    | '/pricing/wallet'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/support/contact'
    | '/support/docs'
    | '/user-profile/$'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/chat'
    | '/create-organization'
    | '/pricing'
    | '/support'
    | '/api/chat-usage'
    | '/organization-profile/$'
    | '/organization-profile/accept-invitation'
    | '/pricing/subscriptions'
    | '/pricing/wallet'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/support/contact'
    | '/support/docs'
    | '/user-profile/$'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/chat'
    | '/create-organization'
    | '/pricing'
    | '/support'
    | '/api/chat-usage'
    | '/organization-profile/$'
    | '/organization-profile/accept-invitation'
    | '/pricing/subscriptions'
    | '/pricing/wallet'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/support/contact'
    | '/support/docs'
    | '/user-profile/$'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  ChatRoute: typeof ChatRoute
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  PricingRoute: typeof PricingRouteWithChildren
  SupportRoute: typeof SupportRouteWithChildren
  ApiChatUsageRoute: typeof ApiChatUsageRoute
  OrganizationProfileSplatRoute: typeof OrganizationProfileSplatRoute
  OrganizationProfileAcceptInvitationRoute: typeof OrganizationProfileAcceptInvitationRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  UserProfileSplatRoute: typeof UserProfileSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-profile/$': {
      id: '/user-profile/$'
      path: '/user-profile/$'
      fullPath: '/user-profile/$'
      preLoaderRoute: typeof UserProfileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/docs': {
      id: '/support/docs'
      path: '/docs'
      fullPath: '/support/docs'
      preLoaderRoute: typeof SupportDocsRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/contact': {
      id: '/support/contact'
      path: '/contact'
      fullPath: '/support/contact'
      preLoaderRoute: typeof SupportContactRouteImport
      parentRoute: typeof SupportRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/wallet': {
      id: '/pricing/wallet'
      path: '/wallet'
      fullPath: '/pricing/wallet'
      preLoaderRoute: typeof PricingWalletRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/subscriptions': {
      id: '/pricing/subscriptions'
      path: '/subscriptions'
      fullPath: '/pricing/subscriptions'
      preLoaderRoute: typeof PricingSubscriptionsRouteImport
      parentRoute: typeof PricingRoute
    }
    '/organization-profile/accept-invitation': {
      id: '/organization-profile/accept-invitation'
      path: '/organization-profile/accept-invitation'
      fullPath: '/organization-profile/accept-invitation'
      preLoaderRoute: typeof OrganizationProfileAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization-profile/$': {
      id: '/organization-profile/$'
      path: '/organization-profile/$'
      fullPath: '/organization-profile/$'
      preLoaderRoute: typeof OrganizationProfileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-usage': {
      id: '/api/chat-usage'
      path: '/api/chat-usage'
      fullPath: '/api/chat-usage'
      preLoaderRoute: typeof ApiChatUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PricingRouteChildren {
  PricingSubscriptionsRoute: typeof PricingSubscriptionsRoute
  PricingWalletRoute: typeof PricingWalletRoute
}

const PricingRouteChildren: PricingRouteChildren = {
  PricingSubscriptionsRoute: PricingSubscriptionsRoute,
  PricingWalletRoute: PricingWalletRoute,
}

const PricingRouteWithChildren =
  PricingRoute._addFileChildren(PricingRouteChildren)

interface SupportRouteChildren {
  SupportContactRoute: typeof SupportContactRoute
  SupportDocsRoute: typeof SupportDocsRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportContactRoute: SupportContactRoute,
  SupportDocsRoute: SupportDocsRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ChatRoute: ChatRoute,
  CreateOrganizationRoute: CreateOrganizationRoute,
  PricingRoute: PricingRouteWithChildren,
  SupportRoute: SupportRouteWithChildren,
  ApiChatUsageRoute: ApiChatUsageRoute,
  OrganizationProfileSplatRoute: OrganizationProfileSplatRoute,
  OrganizationProfileAcceptInvitationRoute:
    OrganizationProfileAcceptInvitationRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  UserProfileSplatRoute: UserProfileSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
